<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:CORE="http://www.caqh.org/SOAP/WSDL/"
             xmlns:tns="urn:gov:hhs:fha:nhinc:adaptercoreresponse"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsaws="http://www.w3.org/2005/08/addressing"
             xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" 
             xmlns:sxnmp="http://www.sun.com/wsbpel/2.0/process/executable/SUNExtension/NMProperty"
             xmlns:x12="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd"
             xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
             name="AdapterCOREResponse"
             targetNamespace="urn:gov:hhs:fha:nhinc:adaptercoreresponse">
    <documentation>CAQH CORE X12 Document Submission Response Secured</documentation>
    <types>
        <xsd:schema xmlns="http://schemas.xmlsoap.org/wsdl/"  elementFormDefault="qualified" targetNamespace="http://www.caqh.org/SOAP/WSDL/">
            <xsd:import namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd" schemaLocation="classpath:schemas/nhin/x12.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:samltokendata" schemaLocation="classpath:schemas/nhinc/gateway/SamlTokenData.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="classpath:schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
    </types>
    <message name="COREEnvelopeBatchSubmissionResponseMessage">
        <part name="body" element="nccommonadapter:AdapterBatchSubmissionResponse"/>
    </message>
    <message name="COREEnvelopeBatchSubmissionAckRetrievalResponse">
        <part name="body" element="x12:X12Acknowledgement"/>
    </message>  
    <portType name="AdapterBatchSubmissionResponse_PortType">
        <operation name="BatchSubmissionResponse">
            <input message="tns:COREEnvelopeBatchSubmissionResponseMessage"/>
            <output message="tns:COREEnvelopeBatchSubmissionAckRetrievalResponse"/>
        </operation>
    </portType>
    <binding name="AdapterBatchSubmissionResponseSoapBinding" type="tns:AdapterBatchSubmissionResponse_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="BatchSubmissionResponse">
            <soap12:operation soapAction="BatchSubmissionResponse" style="document"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="AdapterX12BatchSubmissionResponse">
        <port name="AdapterBatchSubmissionResponse_Port" binding="tns:AdapterBatchSubmissionResponseSoapBinding">
            <soap12:address location="http://localhost:${HttpDefaultPort}/Adapter/X12DocSubmission/AdapterX12DocSubmissionResponseUnsecured"/>
        </port>
    </service>
</definitions>
