<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Adapter Document Query Deferred Response Option Request WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" 
        xmlns="http://schemas.xmlsoap.org/wsdl/" 
        xmlns:tns="urn:gov:hhs:fha:nhinc:dq:adapterdeferredrequestoption"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
        xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
        xmlns:dq="http://www.hhs.gov/healthit/nhin"
        xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
        name="AdapterDeferredResponseOptionRequest" 
        targetNamespace="urn:gov:hhs:fha:nhinc:dq:adapterdeferredrequestoption">
    <documentation>Adapter Document Query Deferred Response Option Request</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="classpath:schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
    </types>
    <message name="RespondingGateway_CrossGatewayQueryDeferredRequestMessage">
        <part name="RespondingGateway_CrossGatewayQueryDeferredRequest" element="nccommonadapter:RespondingGateway_CrossGatewayQueryRequest"/>
    </message>
    <message name="RespondingGateway_CrossGatewayQueryDeferredResponseMessage">
        <part name="RespondingGateway_CrossGatewayQueryDeferredResponse" element="rs:RegistryResponse"/>
    </message>
    <portType name="AdapterDeferredResponseOptionRequestPortType">
        <operation name="RespondingGateway_CrossGatewayQueryDeferred">
            <input name="RespondingGateway_CrossGatewayQueryDeferredRequest" message="tns:RespondingGateway_CrossGatewayQueryDeferredRequestMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:dq:adapterdeferredrequestoption:RespondingGateway_CrossGatewayQueryDeferred" />
            <output name="RespondingGateway_CrossGatewayQueryDeferredResponse" message="tns:RespondingGateway_CrossGatewayQueryDeferredResponseMessage" wsaw:Action="urn:gov:hhs:fha:nhinc:dq:adapterdeferredrequestoption:RespondingGateway_CrossGatewayQueryDeferredResponse"/>
        </operation>
    </portType>
    <binding name="AdapterDeferredResponseOptionRequestBindingSoap" type="tns:AdapterDeferredResponseOptionRequestPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="RespondingGateway_CrossGatewayQueryDeferred">
            <soap:operation soapAction="urn:gov:hhs:fha:nhinc:dq:adapterdeferredrequestoption:RespondingGateway_CrossGatewayQueryDeferred"/>
            <input name="RespondingGateway_CrossGatewayQueryDeferredRequest">
                <soap:body use="literal"/>
            </input>
            <output name="RespondingGateway_CrossGatewayQueryDeferredResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="AdapterDeferredResponseOptionRequest">
        <port name="AdapterDeferredResponseOptionRequestPortSoap"  binding="tns:AdapterDeferredResponseOptionRequestBindingSoap">
            <soap:address
                    location="http://localhost:${HttpDefaultPort}/NhinConnect/AdapterDeferredResponseOptionRequest" />
        </port>
    </service>
</definitions>