<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Deferred Results Option WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/" 
        xmlns="http://schemas.xmlsoap.org/wsdl/" 
        xmlns:tns="urn:gov:hhs:fha:nhinc:dq:nhindeferredresultoption"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
        xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
        xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
        name="DeferredResultsOption" 
        targetNamespace="urn:gov:hhs:fha:nhinc:dq:nhindeferredresultoption">
    <documentation>Deferred Results Option for Document Query</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" schemaLocation="classpath:schemas/ebRS/query.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" schemaLocation="classpath:schemas/ebRS/rs.xsd"/>
        </xsd:schema>
    </types>   
    <message name="RespondingGateway_CrossGatewayQueryDeferredResultsMessage">
        <part name="RespondingGateway_CrossGatewayQueryDeferredResults" element="query:AdhocQueryResponse"/>
    </message>
    <message name="RespondingGateway_CrossGatewayQueryResponseMessage">
        <part name="RespondingGateway_CrossGatewayQueryResponse" element="rs:RegistryResponse"/>
    </message>
     <portType name="DocQueryDeferredResultsPortType">
        <operation name="RespondingGateway_CrossGatewayQueryResults">
            <input name="RespondingGateway_CrossGatewayQueryDeferredResults" message="tns:RespondingGateway_CrossGatewayQueryDeferredResultsMessage" wsaw:Action="tns:RespondingGateway_CrossGatewayQueryDeferredResults" />
            <output name="RespondingGateway_CrossGatewayQueryResponse" message="tns:RespondingGateway_CrossGatewayQueryResponseMessage" wsaw:Action="tns:RespondingGateway_CrossGatewayQueryDeferredResponse"/>
        </operation>
    </portType>
    <binding name="DocumentQueryDeferredResultsBindingSoap" type="tns:DocQueryDeferredResultsPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="RespondingGateway_CrossGatewayQueryResults">
            <soap:operation soapAction="tns:RespondingGateway_CrossGatewayQueryDeferredResults"/>
            <input name="RespondingGateway_CrossGatewayQueryDeferredResults">
                <soap:body use="literal"/>
            </input>
            <output name="RespondingGateway_CrossGatewayQueryResponse">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="DocumentQueryDeferredResults">
        <port name="DocumentQueryDeferredResultsPortSoap"  binding="tns:DocumentQueryDeferredResultsBindingSoap">
            <soap:address location="http://localhost:${HttpDefaultPort}/NhinConnect/DocumentQueryDeferredResults" />
        </port>
    </service>
</definitions>