<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Nhin Deferred Results Option Secured WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:tns="urn:gov:hhs:fha:nhinc:dq:nhindeferredresultsecured" 
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
        xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
        xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
        xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
        xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
        xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
        name="NhinDocQueryDeferredRequestSecured" 
        targetNamespace="urn:gov:hhs:fha:nhinc:dq:nhindeferredresultsecured">
    <documentation>Nhin Deferred Results Option Secured</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" schemaLocation="classpath:schemas/ebRS/rs.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" schemaLocation="classpath:schemas/ebRS/query.xsd"/>
        </xsd:schema>
    </types>
    <message name="CrossGatewayQueryDeferredResults_Message">
        <part name="CrossGatewayQueryDeferredResults" element="query:AdhocQueryResponse"/>
    </message>
    <message name="CrossGatewayQueryDeferredResultsAcknowledgement_Message">
        <part name="CrossGatewayQueryDeferredResultsAcknowledgement" element="rs:RegistryResponse"/>
    </message>
    <portType name="NhinDocQueryDeferredResponseSecuredPortType">
        <operation name="InitiatingGateway_CrossGatewayQueryDeferredResults">
            <input name="CrossGatewayQueryDeferredResults" message="tns:CrossGatewayQueryDeferredResults_Message" wsaw:Action="urn:ihe:iti:2007:CrossGatewayQueryDeferredResults"/>
            <output name="CrossGatewayQueryDeferredResultsAcknowledgement" message="tns:CrossGatewayQueryDeferredResultsAcknowledgement_Message" wsaw:Action="urn:ihe:iti:2007:CrossGatewayQueryDeferredResultsAcknowledgement"/>
        </operation>
    </portType>
    <binding name="NhinDocQueryDeferredResponseSecuredBindingSoap" type="tns:NhinDocQueryDeferredResponseSecuredPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#RespondingGateway_Query_Binding_SoapPolicy"/>
        <operation name="InitiatingGateway_CrossGatewayQueryDeferredResults">
            <soap:operation soapAction="urn:ihe:iti:2007:CrossGatewayQueryDeferredResults"/>
            <input name="CrossGatewayQueryDeferredResults">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_Query_Binding_Soap_Input_Policy"/>
            </input>
            <output name="CrossGatewayQueryDeferredResultsAcknowledgement">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#RespondingGateway_Query_Binding_Soap_Output_Policy"/>
            </output>
        </operation>
    </binding>
    <service name="NhinDocQueryDeferredResponseSecured">
        <port name="NhinDocQueryDeferredRequestSecuredPortSoap" binding="tns:NhinDocQueryDeferredResponseSecuredBindingSoap">
            <soap:address location="https://localhost:${HttpsDefaultPort}/NhinConnect/NhinDocQueryDeferredResponseSecured"/>
        </port>
    </service>

    <wsp:Policy wsu:Id="RespondingGateway_Query_Binding_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                          <wsp:Policy>
                            <wsp:ExactlyOne>
                              <sp:Basic256 />
                              <sp:Basic192 />
                              <sp:Basic128 />
                              <sp:TripleDes />
                              <sp:Basic256Rsa15 />
                              <sp:Basic192Rsa15 />
                              <sp:Basic128Rsa15 />
                              <sp:TripleDesRsa15 />
                              <sp:Basic256Sha256 />
                              <sp:Basic192Sha256 />
                              <sp:Basic128Sha256 />
                              <sp:TripleDesSha256 />
                              <sp:Basic256Sha256Rsa15 />
                              <sp:Basic192Sha256Rsa15 />
                              <sp:Basic128Sha256Rsa15 />
                              <sp:TripleDesSha256Rsa15 />
                            </wsp:ExactlyOne>
                          </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
				<wsaw:UsingAddressing />
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="RespondingGateway_Query_Binding_Soap_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="RespondingGateway_Query_Binding_Soap_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>