<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Adapter Document Query Deferred Response Secured WSDL
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:tns="urn:gov:hhs:fha:nhinc:adapterdocquerydeferredresponsesecured"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:query="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
 xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
 xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
 xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
 xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702"
 xmlns:dq="http://www.hhs.gov/healthit/nhin"
 xmlns:nccommonadapter="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter"
 name="AdapterDocQueryDeferredResponseSecured"
 targetNamespace="urn:gov:hhs:fha:nhinc:adapterdocquerydeferredresponsesecured">
    <documentation>Adapter Document Query Deferred Response Secured</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0" schemaLocation="classpath:schemas/ebRS/query.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin" schemaLocation="classpath:schemas/nhin/QueryDocument.xsd"/>  
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:gateway:samltokendata" schemaLocation="classpath:schemas/nhinc/gateway/SamlTokenData.xsd"/>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonadapter" schemaLocation="classpath:schemas/nhinc/common/NhincCommonAdapter.xsd"/>
        </xsd:schema>
    </types>
    <message name="RespondingGateway_CrossGatewayQueryResponseSecuredMessage">
        <part name="RespondingGateway_CrossGatewayQueryRequest" element="nccommonadapter:RespondingGateway_CrossGatewayQuerySecureResponse"/>
    </message>
    <message name="RespondingGateway_CrossGatewayQueryResponseAckMessage">
        <part name="RespondingGateway_CrossGatewayQueryResponse" element="dq:DocQueryAcknowledgement"/>
    </message>
    <portType name="AdapterDocQueryDeferredResponseSecuredPortType">
        <operation name="RespondingGateway_CrossGatewayQuery">
            <input name="RespondingGateway_CrossGatewayQueryRequest" 
            message="tns:RespondingGateway_CrossGatewayQueryResponseSecuredMessage" 
            wsaw:Action="tns:RespondingGateway_CrossGatewayQueryResponseSecured"/>
            <output name="RespondingGateway_CrossGatewayQueryResponse" 
            message="tns:RespondingGateway_CrossGatewayQueryResponseAckMessage" 
            wsaw:Action="tns:RespondingGateway_CrossGatewayQueryResponseAck"/>
        </operation>
    </portType>
    <binding name="AdapterDocQueryDeferredResponseSecuredBindingSoap" type="tns:AdapterDocQueryDeferredResponseSecuredPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#RespondingGateway_Query_Binding_SoapPolicy"/>
        <operation name="RespondingGateway_CrossGatewayQuery">
            <soap:operation soapAction="tns:RespondingGateway_CrossGatewayQueryResponseSecured"/>
            <input name="RespondingGateway_CrossGatewayQueryRequest">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#Adapter_DocQueryDeferred_Binding_Soap_Input_Policy"/>
            </input>
            <output name="RespondingGateway_CrossGatewayQueryResponse">
                <soap:body use="literal"/>
                <wsp:PolicyReference URI="#Adapter_DocQueryDeferred_Binding_Soap_Output_Policy"/>
            </output>
        </operation>
    </binding>
    <service name="AdapterDocQueryDeferredResponseSecured">
        <port name="AdapterDocQueryDeferredResponseSecuredPortSoap" binding="tns:AdapterDocQueryDeferredResponseSecuredBindingSoap">
            <soap:address location="https://localhost:${HttpsDefaultPort}/NhinConnect/AdapterDocQueryDeferredResponseSecured"/>
        </port>
    </service>
    <wsp:Policy wsu:Id="RespondingGateway_Query_Binding_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                          <wsp:Policy>
                            <wsp:ExactlyOne>
                              <sp:Basic256 />
                            </wsp:ExactlyOne>
                          </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
				<wsaw:UsingAddressing />
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
        <wsp:Policy wsu:Id="Adapter_DocQueryDeferred_Binding_Soap_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
      </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="Adapter_DocQueryDeferred_Binding_Soap_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
      </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</definitions>
