<?xml version="1.0" encoding="UTF-8"?>
<!--
  Entity Document Query Deferred Response
  -->
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:tns="urn:gov:hhs:fha:nhinc:entitydocquerydeferredresponse"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:dq="http://www.hhs.gov/healthit/nhin"
        xmlns:nccommondq="urn:gov:hhs:fha:nhinc:common:nhinccommonentity"
        xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
        name="EntityDocQueryDeferredResponse"
        targetNamespace="urn:gov:hhs:fha:nhinc:entitydocquerydeferredresponse">
    <documentation>Entity Document Query Deferred Response</documentation>
    <types>
        <xsd:schema>
            <xsd:import namespace="urn:gov:hhs:fha:nhinc:common:nhinccommonentity" schemaLocation="classpath:schemas/nhinc/common/NhincCommonEntity.xsd"/>
            <xsd:import namespace="http://www.hhs.gov/healthit/nhin" schemaLocation="classpath:schemas/nhin/QueryDocument.xsd"/>  
        </xsd:schema>
    </types>
    <message name="CrossGatewayDocQueryDeferredResponseMessage">
        <part name="CrossGatewayDocQueryDeferredResponse"
                element="nccommondq:RespondingGateway_CrossGatewayQueryResponse"/>
    </message>
    <message name="CrossGatewayQueryAcknowledgementMessage">
        <part name="CrossGatewayQueryAcknowledgement" element="dq:DocQueryAcknowledgement"/>
    </message>
    <portType name="EntityDocQueryDeferredResponsePortType">
        <operation name="CrossGatewayQueryResponse">
            <input name="CrossGatewayDocQueryDeferredResponseMessage"
                    message="tns:CrossGatewayDocQueryDeferredResponseMessage"
                    wsaw:Action="tns:CrossGatewayDocQueryDeferredResponse"/>
            <output name="CrossGatewayQueryAcknowledgementMessage"
                    message="tns:CrossGatewayQueryAcknowledgementMessage"
                    wsaw:Action="tns:CrossGatewayDocQueryDeferredResponseAck" />
        </operation>
    </portType>
    <binding name="EntityDocQueryDeferredResponseBindingSoap"
            type="tns:EntityDocQueryDeferredResponsePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CrossGatewayQueryResponse">
            <soap:operation soapAction="tns:CrossGatewayDocQueryDeferredResponse"/>
            <input name="CrossGatewayDocQueryDeferredResponseMessage">
                <soap:body use="literal"/>
            </input>
            <output name="CrossGatewayQueryAcknowledgementMessage">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="EntityDocQueryDeferredResponse">
        <port name="EntityDocQueryDeferredResponsePortSoap"
                binding="tns:EntityDocQueryDeferredResponseBindingSoap">
            <soap:address
                    location="http://localhost:${HttpDefaultPort}/NhinConnect/EntityDocQueryDeferredResponse"/>
        </port>
    </service>
</definitions>

