<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:CORE="http://www.caqh.org/SOAP/WSDL/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:CORE-XSD="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" 
                  xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization" 
                  xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" 
                  xmlns:sc="http://schemas.sun.com/2006/03/wss/server" 
                  xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" 
                  xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" 
                  xmlns:sxnmp="http://www.sun.com/wsbpel/2.0/process/executable/SUNExtension/NMProperty"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  name="CORE"
                  targetNamespace="http://www.caqh.org/SOAP/WSDL/">
    <wsdl:types>
        <xsd:schema xmlns="http://schemas.xmlsoap.org/wsdl/"
                    elementFormDefault="qualified"
                    targetNamespace="http://www.caqh.org/SOAP/WSDL/">
            <xsd:import namespace="http://www.caqh.org/SOAP/WSDL/CORERule2.2.0.xsd"
                        schemaLocation="classpath:schemas/caqh/CORERule2.2.0.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="RealTimeRequestMessage">
        <wsdl:part name="body" element="CORE-XSD:COREEnvelopeRealTimeRequest"/>
    </wsdl:message>
    <wsdl:message name="RealTimeResponseMessage">
        <wsdl:part name="body" element="CORE-XSD:COREEnvelopeRealTimeResponse"/>
    </wsdl:message>
    <wsdl:portType name="CORETransactions">
        <wsdl:operation name="RealTimeTransaction">
            <wsdl:input message="CORE:RealTimeRequestMessage" wsaw:Action="RealTimeTransaction"/>
            <wsdl:output message="CORE:RealTimeResponseMessage" wsaw:Action="http://www.caqh.org/SOAP/WSDL/CORETransactions/RealTimeTransactionResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CoreSoapBinding" type="CORE:CORETransactions">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsp:PolicyReference URI="#NwHIN_MessagingPlatform_SoapPolicy"/>
        <wsdl:operation name="RealTimeTransaction">
            <soap12:operation soapAction="RealTimeTransaction" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
                <wsp:PolicyReference URI="#Binding_Soap_Input_Policy"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
                <wsp:PolicyReference URI="#Binding_Soap_Output_Policy"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Core">
        <wsdl:port name="CoreSoapPort" binding="CORE:CoreSoapBinding">
            <soap12:address location="https://localhost:${HttpsDefaultPort}/Gateway/X12CoreRealTime/1_0/X12RealTimeDS_Service"/>
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="NwHIN_MessagingPlatform_SoapPolicy">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding>
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                        <sp:RequireClientCertificate/>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Lax/>
                            </wsp:Policy>
                        </sp:Layout>
                        <sp:IncludeTimestamp/>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                            <wsp:ExactlyOne>
                                <sp:Basic256 />
                                <sp:Basic192 />
                                <sp:Basic128 />
                                <sp:TripleDes />
                                <sp:Basic256Rsa15 />
                                <sp:Basic192Rsa15 />
                                <sp:Basic128Rsa15 />
                                <sp:TripleDesRsa15 />
                                <sp:Basic256Sha256 />
                                <sp:Basic192Sha256 />
                                <sp:Basic128Sha256 />
                                <sp:TripleDesSha256 />
                                <sp:Basic256Sha256Rsa15 />
                                <sp:Basic192Sha256Rsa15 />
                                <sp:Basic128Sha256Rsa15 />
                                <sp:TripleDesSha256Rsa15 />
                                </wsp:ExactlyOne>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                    </wsp:Policy>
                </sp:TransportBinding>
                <sp:EndorsingSupportingTokens>
                    <wsp:Policy>
                        <sp:SamlToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
                            <wsp:Policy>
                                <sp:WssSamlV20Token11/>
                            </wsp:Policy>
                        </sp:SamlToken>
                    </wsp:Policy>
                </sp:EndorsingSupportingTokens>
                <sp:Wss11>
                    <wsp:Policy>
                        <sp:MustSupportRefKeyIdentifier/>
                        <sp:MustSupportRefIssuerSerial/>
                        <sp:RequireSignatureConfirmation/>
                    </wsp:Policy>
                </sp:Wss11>
                <wsaw:UsingAddressing />
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="Binding_Soap_Input_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsp:Policy wsu:Id="Binding_Soap_Output_Policy">
        <wsp:ExactlyOne>
            <wsp:All>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
